version: "3.5"

services:
    beacon:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - /var/lib/lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts:ro
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
#            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        restart: always
        networks:
            - net
    validator:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - /var/lib/lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./validator_keys:/root/validator_keys:ro
        depends_on:
            - beacon_node
#        ports:
#            - 5064:5064/tcp     # metrics endpoint
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        restart: always
        networks:
            - net
    geth:
        image: ethereum/client-go:${GETH_VERSION}
        entrypoint: /bin/sh
        volumes:
            - /var/lib/goethereum:/root/.ethereum
            - ./scripts:/root/scripts:ro
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
#            - 8545:8545 # TODO: remove when switched to lighthouse
        env_file: .env
        command: /root/scripts/start-geth.sh
        restart: always
        networks:
            - net
networks:
    net:
        name: eth2_net
